<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Platform Homepage</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Font Awesome for Book Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/homePage.css">
    <!-- Alternative: Inline CSS for testing -->
    <!-- <link rel="stylesheet" href="${pageContext.request.contextPath}/css/homePage.css"> -->
    <!-- Google Fonts: Inter -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <jsp:include page="navbar.jsp" />

    <!-- Main Content -->
     <c:if test="${not empty sessionScope.username}">
        <h1 class="fw-bold mb-3">Welcome Back, ${sessionScope.username}!</h1>
    </c:if>
    <div class="container mt-4">
        <div class="row">
            <!-- Sidebar with Learning Roadmap -->
            <div class="col-md-3">
                <c:if test="${empty sessionScope.username}">
                <div class="sidebar card p-3">
                    <h1 class="fw-bold mb-3">Welcome to LearnHub</h1>
                    <p class="lead mb-4">
                        Unlock your learning journey! Sign up or log in to access personalized courses, track your progress, and get AI-powered recommendations tailored just for you.
                    </p>
                    <a href="${pageContext.request.contextPath}/login" class="btn btn-primary btn-lg me-3">Login</a>
                    <a href="${pageContext.request.contextPath}/register" class="btn btn-outline-primary btn-lg">Register</a>
                </div></c:if>
                
                <c:if test="${not empty sessionScope.username}">
                <div class="sidebar card p-3">
                    <h4>Learning Roadmap</h4>
                    <ul class="list-group">
                        <li class="list-group-item">Module 1: Introduction
                            <div class="progress mt-2">
                                <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>
                            </div>
                        </li>
                        <li class="list-group-item">Module 2: Intermediate
                            <div class="progress mt-2">
                                <div class="progress-bar" role="progressbar" style="width: 30%;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">30%</div>
                            </div>
                        </li>
                        <li class="list-group-item">Module 3: Advanced
                            <div class="progress mt-2">
                                <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">10%</div>
                            </div>
                        </li>
                    </ul>
                    <a href="roadmap.jsp" class="btn btn-primary mt-3">View Full Roadmap</a>
                </div></c:if>
                
            </div>

            <!-- Course Section -->
            <div class="col-md-9">
                <!-- AI-Powered Featured Courses Section -->
                <c:if test="${not empty featuredCourses && aiFeatured}">
                    <div class="ai-featured-section mb-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h2 class="mb-0">
                                <i class="bi bi-robot text-primary me-2"></i>
                                AI Recommended for You
                            </h2>
                            <span class="badge bg-gradient-primary">
                                <i class="bi bi-cpu me-1"></i>
                                AI Powered
                            </span>
                        </div>
                        <p class="text-muted mb-4">Personalized course recommendations generated by artificial intelligence</p>
                        
                        <div class="row">
                            <c:forEach var="course" items="${featuredCourses}" varStatus="status">
                                <div class="col-md-6 mb-3">
                                    <div class="card featured-course-card h-100 border-0 shadow-sm">
                                        <div class="row g-0">
                                            <div class="col-4">
                                                <img src="${pageContext.request.contextPath}/${course.image}" 
                                                     class="img-fluid rounded-start h-100" 
                                                     alt="${course.name}" 
                                                     style="object-fit: cover;">
                                            </div>
                                            <div class="col-8">
                                                <div class="card-body p-3">
                                                    <div class="d-flex justify-content-between align-items-start mb-2">
                                                        <h6 class="card-title mb-0">${course.name}</h6>
                                                        <span class="badge bg-primary">#${status.index + 1}</span>
                                                    </div>
                                                    <p class="card-text text-muted small mb-2">${course.description}</p>
                                                    <div class="d-flex justify-content-between align-items-center">
                                                        <small class="text-muted">
                                                            <i class="bi bi-play-circle me-1"></i>
                                                            ${course.lectureCount} lessons
                                                        </small>
                                                        <a href="${pageContext.request.contextPath}/course?courseId=${course.idCourse}" 
                                                           class="btn btn-sm btn-outline-primary">Start</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </c:forEach>
                        </div>
                        
                        <div class="text-center mt-3">
                            <a href="${pageContext.request.contextPath}/ai-recommendations" 
                               class="btn btn-primary">
                                <i class="bi bi-lightbulb me-2"></i>
                                Get More AI Recommendations
                            </a>
                        </div>
                    </div>
                </c:if>
                
                <!-- AI Assistant Integration Panel -->
                <c:if test="${aiAssistantAvailable}">
                    <div class="ai-assistant-panel mb-4">
                        <div class="card border-0 bg-gradient-primary text-white">
                            <div class="card-body">
                                <div class="row align-items-center">
                                    <div class="col-md-8">
                                        <h5 class="card-title mb-2">
                                            <i class="bi bi-robot me-2"></i>
                                            Meet Your AI Learning Assistant
                                        </h5>
                                        <p class="card-text mb-0">
                                            Get instant help with programming questions, course recommendations, and personalized learning guidance.
                                        </p>
                                    </div>
                                    <div class="col-md-4 text-md-end">
                                        <button class="btn btn-light btn-lg" onclick="window.aiChatWidget && window.aiChatWidget.open()">
                                            <i class="bi bi-chat-dots me-2"></i>
                                            Ask AI
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </c:if>
                
                <!-- All Courses Section -->
                <div class="all-courses-section">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h2>All Courses</h2>
                        <div class="course-filters">
                            <button class="btn btn-sm btn-outline-secondary me-2" data-filter="all">All</button>
                            <button class="btn btn-sm btn-outline-secondary me-2" data-filter="beginner">Beginner</button>
                            <button class="btn btn-sm btn-outline-secondary me-2" data-filter="intermediate">Intermediate</button>
                            <button class="btn btn-sm btn-outline-secondary" data-filter="advanced">Advanced</button>
                        </div>
                    </div>
                    
                    <c:if test="${not empty error}">
                        <div class="alert alert-danger">${error}</div>
                    </c:if>
                    
                    <div class="row" id="coursesContainer">
                        <c:forEach var="course" items="${courses}">
                            <div class="col-md-4 mb-4 course-item" data-level="beginner">
                                <div class="card course-card h-100">
                                    <img src="${pageContext.request.contextPath}/${course.image}" 
                                         class="card-img-top" 
                                         alt="${course.name}" 
                                         onerror="this.src=''"
                                         style="width: 100%; height: 200px; object-fit: cover;">
                                    <div class="card-body d-flex flex-column">
                                        <h5 class="card-title">${course.name}</h5>
                                        <p class="card-text flex-grow-1">${course.description}</p>
                                        
                                        <div class="course-meta mb-3">
                                            <div class="d-flex justify-content-between align-items-center">
                                                <span class="text-muted small">
                                                    <i class="bi bi-play-circle me-1"></i>
                                                    ${course.lectureCount} lessons
                                                </span>
                                                <c:if test="${not empty course.teacherName}">
                                                    <span class="text-muted small">
                                                        <i class="bi bi-person me-1"></i>
                                                        ${course.teacherName}
                                                    </span>
                                                </c:if>
                                            </div>
                                        </div>
        
                                        <c:if test="${not empty sessionScope.username}">
                                            <div class="progress progress-container mb-2">
                                                <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
                                            </div>
                                            <a href="${pageContext.request.contextPath}/course?courseId=${course.idCourse}" class="btn btn-primary mt-auto">Continue Learning</a>
                                        </c:if>
                                        <c:if test="${empty sessionScope.username}">
                                            <a href="${pageContext.request.contextPath}/course?courseId=${course.idCourse}" class="btn btn-outline-primary mt-auto">View Course Details</a>
                                        </c:if>
                                    </div>
                                </div>
                            </div>
                        </c:forEach>
                    </div>
                </div>
            </div>
    </div>

    <!-- Include AI Chatbot Widget -->
    <jsp:include page="chatbotWidget.jsp" />

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Enhanced Homepage JavaScript -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Course filtering functionality
            const filterButtons = document.querySelectorAll('[data-filter]');
            const courseItems = document.querySelectorAll('.course-item');
            
            filterButtons.forEach(button => {
                button.addEventListener('click', function() {
                    const filter = this.dataset.filter;
                    
                    // Update active button
                    filterButtons.forEach(btn => btn.classList.remove('btn-primary'));
                    filterButtons.forEach(btn => btn.classList.add('btn-outline-secondary'));
                    this.classList.remove('btn-outline-secondary');
                    this.classList.add('btn-primary');
                    
                    // Filter courses
                    courseItems.forEach(item => {
                        if (filter === 'all' || item.dataset.level === filter) {
                            item.style.display = 'block';
                        } else {
                            item.style.display = 'none';
                        }
                    });
                });
            });
            
            // Enhanced course card interactions
            const courseCards = document.querySelectorAll('.course-card');
            courseCards.forEach(card => {
                card.addEventListener('mouseenter', function() {
                    this.style.transform = 'translateY(-5px)';
                    this.style.boxShadow = '0 10px 25px rgba(0,0,0,0.1)';
                });
                
                card.addEventListener('mouseleave', function() {
                    this.style.transform = 'translateY(0)';
                    this.style.boxShadow = '';
                });
            });
            
            // AI feature announcements
            if (typeof window.aiChatWidget !== 'undefined') {
                // Show a subtle notification about AI features
                setTimeout(() => {
                    if (!sessionStorage.getItem('aiFeaturesSeen')) {
                        showAIFeatureNotification();
                        sessionStorage.setItem('aiFeaturesSeen', 'true');
                    }
                }, 3000);
            }
        });
        
        function showAIFeatureNotification() {
            const notification = document.createElement('div');
            notification.className = 'ai-notification';
            notification.innerHTML = `
                <div class="alert alert-info alert-dismissible fade show position-fixed" 
                     style="top: 20px; right: 20px; z-index: 1060; max-width: 300px;">
                    <div class="d-flex align-items-center">
                        <i class="bi bi-robot text-primary me-2"></i>
                        <div>
                            <strong>AI Features Available!</strong><br>
                            <small>Try our AI assistant for personalized help</small>
                        </div>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            `;
            
            document.body.appendChild(notification);
            
            // Auto-remove after 5 seconds
            setTimeout(() => {
                const alert = notification.querySelector('.alert');
                if (alert) {
                    bootstrap.Alert.getOrCreateInstance(alert).close();
                }
            }, 5000);
        }
    </script>
    
    <!-- Additional AI-Enhanced Styling -->
    <style>
        .ai-featured-section {
            background: linear-gradient(135deg, #f8f9ff 0%, #e3f2fd 100%);
            border-radius: 15px;
            padding: 2rem;
            border: 1px solid #e1f5fe;
        }
        
        .featured-course-card {
            transition: all 0.3s ease;
            border-radius: 10px;
            overflow: hidden;
        }
        
        .featured-course-card:hover {
            transform: translateY(-3px);
            box-shadow: 0 8px 25px rgba(0,0,0,0.1);
        }
        
        .bg-gradient-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }
        
        .ai-assistant-panel {
            animation: slideInFromRight 0.8s ease-out;
        }
        
        @keyframes slideInFromRight {
            from {
                opacity: 0;
                transform: translateX(30px);
            }
            to {
                opacity: 1;
                transform: translateX(0);
            }
        }
        
        .course-card {
            transition: all 0.3s ease;
            border-radius: 10px;
            overflow: hidden;
        }
        
        .course-meta {
            border-top: 1px solid #f0f0f0;
            padding-top: 0.75rem;
        }
        
        .course-filters .btn {
            transition: all 0.2s ease;
        }
        
        .badge.bg-gradient-primary {
            background: linear-gradient(45deg, #667eea 0%, #764ba2 100%) !important;
        }
        
        .ai-notification {
            animation: slideInFromRight 0.5s ease-out;
        }
        
        /* Responsive adjustments */
        @media (max-width: 768px) {
            .ai-featured-section {
                padding: 1rem;
            }
            
            .course-filters {
                display: flex;
                flex-wrap: wrap;
                gap: 0.5rem;
            }
            
            .course-filters .btn {
                font-size: 0.8rem;
                padding: 0.25rem 0.5rem;
            }
        }
    </style>
</body>
</html>